Common:
  display_name: <green>Common Crate
  crate_item: COMMON_KEY
  menu:
    rows: 3
    background: BACKGROUND_ITEM
    '11': RELIC

  rewards:
    '1':
      weight: 50
      command: "sdklfjsdkf"