#
# Every available setting is already being used in the default config unless specified otherwise
#

EXPLOSIVE:
  name: <gray>Explosive
  description: <reset><gray>Chance to create a big explosion causing all blocks in it's path to shatter
  max_level: 10000
  base_cost: 10000
  cost_increase: 100
  chance_at_max_level: 5
  base_chance: 0.2
  radius: 15
  currency: tokens

JACKHAMMER:
  name: <gray>Jackhammer
  description: <reset><gray>Chance to destroy a whole layer of your mine!
  max_level: 10000
  base_cost: 10000
  cost_increase:  100
  chance_at_max_level: 2
  base_chance: 0.1
  currency: tokens

LUCKY:
  name: <gray>Lucky
  description: <reset><gray>Chance to gain a random amount of tokens!
  max_level: 10000
  base_cost: 10000
  cost_increase:  100
  chance_at_max_level: 5
  base_chance: 0.5
  min_amount: 10000
  max_amount: 50000
  scale_amount: 1.01 # how much should it increase each level!
  currency: tokens

FORTUNE:
  name: <gray>Fortune
  description: <reset><gray>Get more blocks while mining!
  max_level: 10000
  base_cost: 10000
  cost_increase: 100
  base_chance: 100
  currency: tokens

LIGHTNING:
  name: <gray>Lightning
  description: <reset><gray>Chance for lightning to be summoned and create a massive explosion!
  max_level: 10000
  base_cost: 10000
  cost_increase:  100
  chance_at_max_level: 0.05
  base_chance: 0.05
  radius: 10
  currency: tokens

ECLIPSE:
  name: <gray>Eclipse
  description: <reset><gray>Chance to create a shadow zone around the mined block, breaking everything within the zone radius.
  max_level: 10000
  base_cost: 10000
  cost_increase:  100
  chance_at_max_level: 1
  base_chance: 0.05
  radius: 10
  currency: tokens

QUANTUM_MINER:
  name: <gray>Quantum Miner
  description: <reset><gray>Each mined block has a chance to clone itself into 2-5 additional blocks in your inventory/backpack
  max_level: 10000
  base_cost: 10000
  cost_increase: 100
  chance_at_max_level: 25
  base_chance: 0.5
  min_blocks: 2 # These values are INCLUSIVE
  max_blocks: 5
  currency: tokens

AETHER_SURGE:
  name: <gray>Aether Surge
  description: <reset><gray>Occasionally creates an aether storm while mining, boosting rewards for a short time.
  max_level: 10000
  base_cost: 10000
  cost_increase: 100
  chance_at_max_level: 1
  base_chance: 0.1
  boost_amount: 5
  currency: tokens

STAR_CORE:
  name: <gray>Star Core
  description: <reset><gray>Has a small chance to spawn a Star Core, a rare consumable block that can be broken for ultra-valuable rewards!
  max_level: 10000
  base_cost: 10000
  cost_increase: 100
  chance_at_max_level: 1
  base_chance: 0.01
  rewards:
    - give %player% diamond_pickaxe 1
  currency: tokens

COSMIC_RIFT:
  name: <gray>Cosmic Rift
  description: <reset><gray>Creates a temporary portal that sucks up blocks in a large sphere!
  max_level: 10000
  base_cost: 10000
  cost_increase: 100
  chance_at_max_level: 2
  base_chance: 0.01
  radius: 20
  currency: tokens

STARFALL:
  name: <gray>Starfall
  description: <reset><gray>Summons shooting stars that break blocks in random patterns!
  max_level: 10000
  base_cost: 10000
  cost_increases: 100
  chance_at_max_level: 5
  base_chance: 0.02
  currency: tokens

RELIC_SEEKER:
  name: <gray>Relic Seeker
  description: <reset><gray>Has a small chance to drop an ancient relic, which can be traded for high rewards!
  max_level: 10000
  base_cost: 10000
  cost_increases: 100
  chance_at_max_level: 1
  base_chance: 0.01
  currency: tokens

COSMIC_BLESSING:
  name: <gray>Cosmic Blessing
  description: <reset><gray>Occasionally grants random buffs or boosts
  max_level: 10000
  base_cost: 10000
  cost_increase: 100
  chance_at_max_level: 2
  base_chance: 0.01
  min_multiplier: 2
  max_multiplier: 5
  currency: tokens

OMNI_TREASURE:
  name: <gray>Omni Treasure
  description: <reset><gray>Mined blocks have a very rare chance to drop an Omni crate, containing items, tokens, money and EXP
  max_level: 10000
  base_cost: 10000
  cost_increase: 100
  chance_at_max_level: 2
  base_chance: 0.02
  currency: tokens

ECHO_OF_THE_DEEP:
  name: <gray>Echo Of The Deep
  description: <reset><gray>Has a small chance to buff your lucky blocks for 30 seconds!
  max_level: 10000
  base_cost: 10000
  cost_increase: 100
  chance_at_max_level: 2
  base_chance: 0.02
  currency: tokens