RELIC:
  name: <purple>Relic
  material: NETHER_STAR
  lore:
    - "test"
    - "test"
  shiny: false


BACKGROUND_ITEM:
  name: ""
  material: BLACK_STAINED_GLASS_PANE
  lore:
    - ""
  shiny: false