RELIC:
  name: <purple> Relic
  material: NETHER_STAR
  lore:
    - "<red>test"
    - "<green>test"
  shiny: false

BACKGROUND_ITEM:
  name: ""
  material: BLACK_STAINED_GLASS_PANE
  lore:
    - ""
  shiny: false


COMMON_KEY:
  name: "<gray>Common Key"
  material: TRIPWIRE_HOOK
  lore:
    - ""
  shiny: true